# Generated by Django 2.2.18 on 2022-06-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ชื่อ')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('gender', models.CharField(choices=[('F', 'หญิง'), ('M', 'ชาย')], default='F', max_length=1, verbose_name='เพศ')),
                ('birthdate', models.DateField(verbose_name='วันเดือนปีเกิด')),
                ('fruit', models.CharField(choices=[('a', 'แอปเปิ้ล'), ('b', 'มะละกอ'), ('c', 'กล้วย'), ('d', 'ส้ม')], default='c', max_length=1, verbose_name='ผลไม้ที่ท่านชอบ')),
                ('comment', models.TextField(blank=True, verbose_name='ข้อเสนอแนะ')),
            ],
        ),
    ]
